name: test

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  GOPROXY: https://proxy.golang.org/

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        go:
          - "1.20"
          - "1.21"
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ matrix.go }}
      - name: Go mod download
        run: go mod download -x
      - name: Go mod verify
        run: go mod verify
      - name: Run tests
        run: go test -count=1 -v ./...

  ci:
    needs:
      - test
    runs-on: ubuntu-20.04
    steps:
      - name: Required Checks
        run: echo "All required checks worked"
